/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AstrologiaRouteImport } from './routes/astrologia'
import { Route as EnRouteImport } from './routes/en'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GdzieDzialamRouteImport } from './routes/gdzie-dzialam'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KronikaRouteImport } from './routes/kronika'
import { Route as OMnieRouteImport } from './routes/o-mnie'
import { Route as PlRouteImport } from './routes/pl'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as PowrotRouteImport } from './routes/powrot'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as RezerwacjaRouteImport } from './routes/rezerwacja'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SanktuariumRouteImport } from './routes/sanktuarium'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAktywnoscRouteImport } from './routes/admin.aktywnosc'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminGrafikRouteImport } from './routes/admin.grafik'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminKonsultacjeRouteImport } from './routes/admin.konsultacje'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminTelegramRouteImport } from './routes/admin.telegram'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BibliotekaIndexRouteImport } from './routes/biblioteka.index'
import { Route as BibliotekaSlugRouteImport } from './routes/biblioteka.$slug'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnAstrologyRouteImport } from './routes/en.astrology'
import { Route as EnBookingRouteImport } from './routes/en.booking'
import { Route as EnChronicleRouteImport } from './routes/en.chronicle'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnFaqRouteImport } from './routes/en.faq'
import { Route as EnPrivacyPolicyRouteImport } from './routes/en.privacy-policy'
import { Route as EnReturnRouteImport } from './routes/en.return'
import { Route as EnSanctuaryRouteImport } from './routes/en.sanctuary'
import { Route as EnServicesRouteImport } from './routes/en.services'
import { Route as EnTarotRouteImport } from './routes/en.tarot'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as EnWhereIWorkRouteImport } from './routes/en.where-i-work'
import { Route as KronikaIndexRouteImport } from './routes/kronika.index'
import { Route as KronikaKonsultacjeRouteImport } from './routes/kronika.konsultacje'
import { Route as KronikaNotatkiRouteImport } from './routes/kronika.notatki'
import { Route as KronikaProfilRouteImport } from './routes/kronika.profil'
import { Route as KronikaRefleksjeRouteImport } from './routes/kronika.refleksje'
import { Route as KronikaRytualyRouteImport } from './routes/kronika.rytualy'
import { Route as PlIndexRouteImport } from './routes/pl.index'
import { Route as PlAstrologiaRouteImport } from './routes/pl.astrologia'
import { Route as PlFaqRouteImport } from './routes/pl.faq'
import { Route as PlGdzieDzialamRouteImport } from './routes/pl.gdzie-dzialam'
import { Route as PlKontaktRouteImport } from './routes/pl.kontakt'
import { Route as PlKronikaRouteImport } from './routes/pl.kronika'
import { Route as PlOMnieRouteImport } from './routes/pl.o-mnie'
import { Route as PlPolitykaPrywatnosciRouteImport } from './routes/pl.polityka-prywatnosci'
import { Route as PlPowrotRouteImport } from './routes/pl.powrot'
import { Route as PlRegulaminRouteImport } from './routes/pl.regulamin'
import { Route as PlRezerwacjaRouteImport } from './routes/pl.rezerwacja'
import { Route as PlSanktuariumRouteImport } from './routes/pl.sanktuarium'
import { Route as PlTarotRouteImport } from './routes/pl.tarot'
import { Route as PlUslugiRouteImport } from './routes/pl.uslugi'
import { Route as RytualyIndexRouteImport } from './routes/rytualy.index'
import { Route as RytualySlugRouteImport } from './routes/rytualy.$slug'
import { Route as EnChronicleIndexRouteImport } from './routes/en.chronicle.index'
import { Route as EnChronicleConsultationsRouteImport } from './routes/en.chronicle.consultations'
import { Route as EnChronicleNotesRouteImport } from './routes/en.chronicle.notes'
import { Route as EnChronicleProfileRouteImport } from './routes/en.chronicle.profile'
import { Route as EnChronicleReflectionsRouteImport } from './routes/en.chronicle.reflections'
import { Route as EnChronicleRitualsRouteImport } from './routes/en.chronicle.rituals'
import { Route as EnLibraryIndexRouteImport } from './routes/en.library.index'
import { Route as EnLibrarySlugRouteImport } from './routes/en.library.$slug'
import { Route as EnRitualsIndexRouteImport } from './routes/en.rituals.index'
import { Route as EnRitualsSlugRouteImport } from './routes/en.rituals.$slug'
import { Route as PlBibliotekaIndexRouteImport } from './routes/pl.biblioteka.index'
import { Route as PlBibliotekaSlugRouteImport } from './routes/pl.biblioteka.$slug'
import { Route as PlKronikaIndexRouteImport } from './routes/pl.kronika.index'
import { Route as PlKronikaKonsultacjeRouteImport } from './routes/pl.kronika.konsultacje'
import { Route as PlKronikaNotatkiRouteImport } from './routes/pl.kronika.notatki'
import { Route as PlKronikaProfilRouteImport } from './routes/pl.kronika.profil'
import { Route as PlKronikaRefleksjeRouteImport } from './routes/pl.kronika.refleksje'
import { Route as PlKronikaRytualyRouteImport } from './routes/pl.kronika.rytualy'
import { Route as PlRytualyIndexRouteImport } from './routes/pl.rytualy.index'
import { Route as PlRytualySlugRouteImport } from './routes/pl.rytualy.$slug'
import { Route as ApiPublicTelegramAdminRouteImport } from './routes/api/public/telegram/admin'
import { Route as ApiPublicTelegramStatsRouteImport } from './routes/api/public/telegram/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaRoute = AstrologiaRouteImport.update({
  id: '/astrologia',
  path: '/astrologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GdzieDzialamRoute = GdzieDzialamRouteImport.update({
  id: '/gdzie-dzialam',
  path: '/gdzie-dzialam',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KronikaRoute = KronikaRouteImport.update({
  id: '/kronika',
  path: '/kronika',
  getParentRoute: () => rootRouteImport,
} as any)
const OMnieRoute = OMnieRouteImport.update({
  id: '/o-mnie',
  path: '/o-mnie',
  getParentRoute: () => rootRouteImport,
} as any)
const PlRoute = PlRouteImport.update({
  id: '/pl',
  path: '/pl',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const PowrotRoute = PowrotRouteImport.update({
  id: '/powrot',
  path: '/powrot',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const RezerwacjaRoute = RezerwacjaRouteImport.update({
  id: '/rezerwacja',
  path: '/rezerwacja',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SanktuariumRoute = SanktuariumRouteImport.update({
  id: '/sanktuarium',
  path: '/sanktuarium',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAktywnoscRoute = AdminAktywnoscRouteImport.update({
  id: '/aktywnosc',
  path: '/aktywnosc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrafikRoute = AdminGrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKonsultacjeRoute = AdminKonsultacjeRouteImport.update({
  id: '/konsultacje',
  path: '/konsultacje',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BibliotekaIndexRoute = BibliotekaIndexRouteImport.update({
  id: '/biblioteka/',
  path: '/biblioteka/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotekaSlugRoute = BibliotekaSlugRouteImport.update({
  id: '/biblioteka/$slug',
  path: '/biblioteka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const EnAstrologyRoute = EnAstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => EnRoute,
} as any)
const EnBookingRoute = EnBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => EnRoute,
} as any)
const EnChronicleRoute = EnChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyPolicyRoute = EnPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => EnRoute,
} as any)
const EnReturnRoute = EnReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => EnRoute,
} as any)
const EnSanctuaryRoute = EnSanctuaryRouteImport.update({
  id: '/sanctuary',
  path: '/sanctuary',
  getParentRoute: () => EnRoute,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => EnRoute,
} as any)
const EnTarotRoute = EnTarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => EnRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRoute,
} as any)
const EnWhereIWorkRoute = EnWhereIWorkRouteImport.update({
  id: '/where-i-work',
  path: '/where-i-work',
  getParentRoute: () => EnRoute,
} as any)
const KronikaIndexRoute = KronikaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KronikaRoute,
} as any)
const KronikaKonsultacjeRoute = KronikaKonsultacjeRouteImport.update({
  id: '/konsultacje',
  path: '/konsultacje',
  getParentRoute: () => KronikaRoute,
} as any)
const KronikaNotatkiRoute = KronikaNotatkiRouteImport.update({
  id: '/notatki',
  path: '/notatki',
  getParentRoute: () => KronikaRoute,
} as any)
const KronikaProfilRoute = KronikaProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => KronikaRoute,
} as any)
const KronikaRefleksjeRoute = KronikaRefleksjeRouteImport.update({
  id: '/refleksje',
  path: '/refleksje',
  getParentRoute: () => KronikaRoute,
} as any)
const KronikaRytualyRoute = KronikaRytualyRouteImport.update({
  id: '/rytualy',
  path: '/rytualy',
  getParentRoute: () => KronikaRoute,
} as any)
const PlIndexRoute = PlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlRoute,
} as any)
const PlAstrologiaRoute = PlAstrologiaRouteImport.update({
  id: '/astrologia',
  path: '/astrologia',
  getParentRoute: () => PlRoute,
} as any)
const PlFaqRoute = PlFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PlRoute,
} as any)
const PlGdzieDzialamRoute = PlGdzieDzialamRouteImport.update({
  id: '/gdzie-dzialam',
  path: '/gdzie-dzialam',
  getParentRoute: () => PlRoute,
} as any)
const PlKontaktRoute = PlKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => PlRoute,
} as any)
const PlKronikaRoute = PlKronikaRouteImport.update({
  id: '/kronika',
  path: '/kronika',
  getParentRoute: () => PlRoute,
} as any)
const PlOMnieRoute = PlOMnieRouteImport.update({
  id: '/o-mnie',
  path: '/o-mnie',
  getParentRoute: () => PlRoute,
} as any)
const PlPolitykaPrywatnosciRoute = PlPolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => PlRoute,
} as any)
const PlPowrotRoute = PlPowrotRouteImport.update({
  id: '/powrot',
  path: '/powrot',
  getParentRoute: () => PlRoute,
} as any)
const PlRegulaminRoute = PlRegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => PlRoute,
} as any)
const PlRezerwacjaRoute = PlRezerwacjaRouteImport.update({
  id: '/rezerwacja',
  path: '/rezerwacja',
  getParentRoute: () => PlRoute,
} as any)
const PlSanktuariumRoute = PlSanktuariumRouteImport.update({
  id: '/sanktuarium',
  path: '/sanktuarium',
  getParentRoute: () => PlRoute,
} as any)
const PlTarotRoute = PlTarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => PlRoute,
} as any)
const PlUslugiRoute = PlUslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => PlRoute,
} as any)
const RytualyIndexRoute = RytualyIndexRouteImport.update({
  id: '/rytualy/',
  path: '/rytualy/',
  getParentRoute: () => rootRouteImport,
} as any)
const RytualySlugRoute = RytualySlugRouteImport.update({
  id: '/rytualy/$slug',
  path: '/rytualy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnChronicleIndexRoute = EnChronicleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnChronicleRoute,
} as any)
const EnChronicleConsultationsRoute =
  EnChronicleConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => EnChronicleRoute,
  } as any)
const EnChronicleNotesRoute = EnChronicleNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => EnChronicleRoute,
} as any)
const EnChronicleProfileRoute = EnChronicleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EnChronicleRoute,
} as any)
const EnChronicleReflectionsRoute = EnChronicleReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => EnChronicleRoute,
} as any)
const EnChronicleRitualsRoute = EnChronicleRitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => EnChronicleRoute,
} as any)
const EnLibraryIndexRoute = EnLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => EnRoute,
} as any)
const EnLibrarySlugRoute = EnLibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => EnRoute,
} as any)
const EnRitualsIndexRoute = EnRitualsIndexRouteImport.update({
  id: '/rituals/',
  path: '/rituals/',
  getParentRoute: () => EnRoute,
} as any)
const EnRitualsSlugRoute = EnRitualsSlugRouteImport.update({
  id: '/rituals/$slug',
  path: '/rituals/$slug',
  getParentRoute: () => EnRoute,
} as any)
const PlBibliotekaIndexRoute = PlBibliotekaIndexRouteImport.update({
  id: '/biblioteka/',
  path: '/biblioteka/',
  getParentRoute: () => PlRoute,
} as any)
const PlBibliotekaSlugRoute = PlBibliotekaSlugRouteImport.update({
  id: '/biblioteka/$slug',
  path: '/biblioteka/$slug',
  getParentRoute: () => PlRoute,
} as any)
const PlKronikaIndexRoute = PlKronikaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlKronikaRoute,
} as any)
const PlKronikaKonsultacjeRoute = PlKronikaKonsultacjeRouteImport.update({
  id: '/konsultacje',
  path: '/konsultacje',
  getParentRoute: () => PlKronikaRoute,
} as any)
const PlKronikaNotatkiRoute = PlKronikaNotatkiRouteImport.update({
  id: '/notatki',
  path: '/notatki',
  getParentRoute: () => PlKronikaRoute,
} as any)
const PlKronikaProfilRoute = PlKronikaProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PlKronikaRoute,
} as any)
const PlKronikaRefleksjeRoute = PlKronikaRefleksjeRouteImport.update({
  id: '/refleksje',
  path: '/refleksje',
  getParentRoute: () => PlKronikaRoute,
} as any)
const PlKronikaRytualyRoute = PlKronikaRytualyRouteImport.update({
  id: '/rytualy',
  path: '/rytualy',
  getParentRoute: () => PlKronikaRoute,
} as any)
const PlRytualyIndexRoute = PlRytualyIndexRouteImport.update({
  id: '/rytualy/',
  path: '/rytualy/',
  getParentRoute: () => PlRoute,
} as any)
const PlRytualySlugRoute = PlRytualySlugRouteImport.update({
  id: '/rytualy/$slug',
  path: '/rytualy/$slug',
  getParentRoute: () => PlRoute,
} as any)
const ApiPublicTelegramAdminRoute = ApiPublicTelegramAdminRouteImport.update({
  id: '/api/public/telegram/admin',
  path: '/api/public/telegram/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramStatsRoute = ApiPublicTelegramStatsRouteImport.update({
  id: '/api/public/telegram/stats',
  path: '/api/public/telegram/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/astrologia': typeof AstrologiaRoute
  '/en': typeof EnRouteWithChildren
  '/faq': typeof FaqRoute
  '/gdzie-dzialam': typeof GdzieDzialamRoute
  '/kontakt': typeof KontaktRoute
  '/kronika': typeof KronikaRouteWithChildren
  '/o-mnie': typeof OMnieRoute
  '/pl': typeof PlRouteWithChildren
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/powrot': typeof PowrotRoute
  '/regulamin': typeof RegulaminRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sanktuarium': typeof SanktuariumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarot': typeof TarotRoute
  '/uslugi': typeof UslugiRoute
  '/admin/aktywnosc': typeof AdminAktywnoscRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/grafik': typeof AdminGrafikRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/konsultacje': typeof AdminKonsultacjeRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/users': typeof AdminUsersRoute
  '/biblioteka/$slug': typeof BibliotekaSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/astrology': typeof EnAstrologyRoute
  '/en/booking': typeof EnBookingRoute
  '/en/chronicle': typeof EnChronicleRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRoute
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/return': typeof EnReturnRoute
  '/en/sanctuary': typeof EnSanctuaryRoute
  '/en/services': typeof EnServicesRoute
  '/en/tarot': typeof EnTarotRoute
  '/en/terms': typeof EnTermsRoute
  '/en/where-i-work': typeof EnWhereIWorkRoute
  '/kronika/konsultacje': typeof KronikaKonsultacjeRoute
  '/kronika/notatki': typeof KronikaNotatkiRoute
  '/kronika/profil': typeof KronikaProfilRoute
  '/kronika/refleksje': typeof KronikaRefleksjeRoute
  '/kronika/rytualy': typeof KronikaRytualyRoute
  '/pl/astrologia': typeof PlAstrologiaRoute
  '/pl/faq': typeof PlFaqRoute
  '/pl/gdzie-dzialam': typeof PlGdzieDzialamRoute
  '/pl/kontakt': typeof PlKontaktRoute
  '/pl/kronika': typeof PlKronikaRouteWithChildren
  '/pl/o-mnie': typeof PlOMnieRoute
  '/pl/polityka-prywatnosci': typeof PlPolitykaPrywatnosciRoute
  '/pl/powrot': typeof PlPowrotRoute
  '/pl/regulamin': typeof PlRegulaminRoute
  '/pl/rezerwacja': typeof PlRezerwacjaRoute
  '/pl/sanktuarium': typeof PlSanktuariumRoute
  '/pl/tarot': typeof PlTarotRoute
  '/pl/uslugi': typeof PlUslugiRoute
  '/rytualy/$slug': typeof RytualySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/biblioteka/': typeof BibliotekaIndexRoute
  '/en/': typeof EnIndexRoute
  '/kronika/': typeof KronikaIndexRoute
  '/pl/': typeof PlIndexRoute
  '/rytualy/': typeof RytualyIndexRoute
  '/en/chronicle/consultations': typeof EnChronicleConsultationsRoute
  '/en/chronicle/notes': typeof EnChronicleNotesRoute
  '/en/chronicle/profile': typeof EnChronicleProfileRoute
  '/en/chronicle/reflections': typeof EnChronicleReflectionsRoute
  '/en/chronicle/rituals': typeof EnChronicleRitualsRoute
  '/en/library/$slug': typeof EnLibrarySlugRoute
  '/en/rituals/$slug': typeof EnRitualsSlugRoute
  '/pl/biblioteka/$slug': typeof PlBibliotekaSlugRoute
  '/pl/kronika/konsultacje': typeof PlKronikaKonsultacjeRoute
  '/pl/kronika/notatki': typeof PlKronikaNotatkiRoute
  '/pl/kronika/profil': typeof PlKronikaProfilRoute
  '/pl/kronika/refleksje': typeof PlKronikaRefleksjeRoute
  '/pl/kronika/rytualy': typeof PlKronikaRytualyRoute
  '/pl/rytualy/$slug': typeof PlRytualySlugRoute
  '/en/chronicle/': typeof EnChronicleIndexRoute
  '/en/library/': typeof EnLibraryIndexRoute
  '/en/rituals/': typeof EnRitualsIndexRoute
  '/pl/biblioteka/': typeof PlBibliotekaIndexRoute
  '/pl/kronika/': typeof PlKronikaIndexRoute
  '/pl/rytualy/': typeof PlRytualyIndexRoute
  '/api/public/telegram/admin': typeof ApiPublicTelegramAdminRoute
  '/api/public/telegram/stats': typeof ApiPublicTelegramStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrologia': typeof AstrologiaRoute
  '/faq': typeof FaqRoute
  '/gdzie-dzialam': typeof GdzieDzialamRoute
  '/kontakt': typeof KontaktRoute
  '/o-mnie': typeof OMnieRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/powrot': typeof PowrotRoute
  '/regulamin': typeof RegulaminRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sanktuarium': typeof SanktuariumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarot': typeof TarotRoute
  '/uslugi': typeof UslugiRoute
  '/admin/aktywnosc': typeof AdminAktywnoscRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/grafik': typeof AdminGrafikRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/konsultacje': typeof AdminKonsultacjeRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/users': typeof AdminUsersRoute
  '/biblioteka/$slug': typeof BibliotekaSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/astrology': typeof EnAstrologyRoute
  '/en/booking': typeof EnBookingRoute
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRoute
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/return': typeof EnReturnRoute
  '/en/sanctuary': typeof EnSanctuaryRoute
  '/en/services': typeof EnServicesRoute
  '/en/tarot': typeof EnTarotRoute
  '/en/terms': typeof EnTermsRoute
  '/en/where-i-work': typeof EnWhereIWorkRoute
  '/kronika/konsultacje': typeof KronikaKonsultacjeRoute
  '/kronika/notatki': typeof KronikaNotatkiRoute
  '/kronika/profil': typeof KronikaProfilRoute
  '/kronika/refleksje': typeof KronikaRefleksjeRoute
  '/kronika/rytualy': typeof KronikaRytualyRoute
  '/pl/astrologia': typeof PlAstrologiaRoute
  '/pl/faq': typeof PlFaqRoute
  '/pl/gdzie-dzialam': typeof PlGdzieDzialamRoute
  '/pl/kontakt': typeof PlKontaktRoute
  '/pl/o-mnie': typeof PlOMnieRoute
  '/pl/polityka-prywatnosci': typeof PlPolitykaPrywatnosciRoute
  '/pl/powrot': typeof PlPowrotRoute
  '/pl/regulamin': typeof PlRegulaminRoute
  '/pl/rezerwacja': typeof PlRezerwacjaRoute
  '/pl/sanktuarium': typeof PlSanktuariumRoute
  '/pl/tarot': typeof PlTarotRoute
  '/pl/uslugi': typeof PlUslugiRoute
  '/rytualy/$slug': typeof RytualySlugRoute
  '/admin': typeof AdminIndexRoute
  '/biblioteka': typeof BibliotekaIndexRoute
  '/en': typeof EnIndexRoute
  '/kronika': typeof KronikaIndexRoute
  '/pl': typeof PlIndexRoute
  '/rytualy': typeof RytualyIndexRoute
  '/en/chronicle/consultations': typeof EnChronicleConsultationsRoute
  '/en/chronicle/notes': typeof EnChronicleNotesRoute
  '/en/chronicle/profile': typeof EnChronicleProfileRoute
  '/en/chronicle/reflections': typeof EnChronicleReflectionsRoute
  '/en/chronicle/rituals': typeof EnChronicleRitualsRoute
  '/en/library/$slug': typeof EnLibrarySlugRoute
  '/en/rituals/$slug': typeof EnRitualsSlugRoute
  '/pl/biblioteka/$slug': typeof PlBibliotekaSlugRoute
  '/pl/kronika/konsultacje': typeof PlKronikaKonsultacjeRoute
  '/pl/kronika/notatki': typeof PlKronikaNotatkiRoute
  '/pl/kronika/profil': typeof PlKronikaProfilRoute
  '/pl/kronika/refleksje': typeof PlKronikaRefleksjeRoute
  '/pl/kronika/rytualy': typeof PlKronikaRytualyRoute
  '/pl/rytualy/$slug': typeof PlRytualySlugRoute
  '/en/chronicle': typeof EnChronicleIndexRoute
  '/en/library': typeof EnLibraryIndexRoute
  '/en/rituals': typeof EnRitualsIndexRoute
  '/pl/biblioteka': typeof PlBibliotekaIndexRoute
  '/pl/kronika': typeof PlKronikaIndexRoute
  '/pl/rytualy': typeof PlRytualyIndexRoute
  '/api/public/telegram/admin': typeof ApiPublicTelegramAdminRoute
  '/api/public/telegram/stats': typeof ApiPublicTelegramStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/astrologia': typeof AstrologiaRoute
  '/en': typeof EnRouteWithChildren
  '/faq': typeof FaqRoute
  '/gdzie-dzialam': typeof GdzieDzialamRoute
  '/kontakt': typeof KontaktRoute
  '/kronika': typeof KronikaRouteWithChildren
  '/o-mnie': typeof OMnieRoute
  '/pl': typeof PlRouteWithChildren
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/powrot': typeof PowrotRoute
  '/regulamin': typeof RegulaminRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sanktuarium': typeof SanktuariumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarot': typeof TarotRoute
  '/uslugi': typeof UslugiRoute
  '/admin/aktywnosc': typeof AdminAktywnoscRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/grafik': typeof AdminGrafikRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/konsultacje': typeof AdminKonsultacjeRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/users': typeof AdminUsersRoute
  '/biblioteka/$slug': typeof BibliotekaSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/astrology': typeof EnAstrologyRoute
  '/en/booking': typeof EnBookingRoute
  '/en/chronicle': typeof EnChronicleRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRoute
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/return': typeof EnReturnRoute
  '/en/sanctuary': typeof EnSanctuaryRoute
  '/en/services': typeof EnServicesRoute
  '/en/tarot': typeof EnTarotRoute
  '/en/terms': typeof EnTermsRoute
  '/en/where-i-work': typeof EnWhereIWorkRoute
  '/kronika/konsultacje': typeof KronikaKonsultacjeRoute
  '/kronika/notatki': typeof KronikaNotatkiRoute
  '/kronika/profil': typeof KronikaProfilRoute
  '/kronika/refleksje': typeof KronikaRefleksjeRoute
  '/kronika/rytualy': typeof KronikaRytualyRoute
  '/pl/astrologia': typeof PlAstrologiaRoute
  '/pl/faq': typeof PlFaqRoute
  '/pl/gdzie-dzialam': typeof PlGdzieDzialamRoute
  '/pl/kontakt': typeof PlKontaktRoute
  '/pl/kronika': typeof PlKronikaRouteWithChildren
  '/pl/o-mnie': typeof PlOMnieRoute
  '/pl/polityka-prywatnosci': typeof PlPolitykaPrywatnosciRoute
  '/pl/powrot': typeof PlPowrotRoute
  '/pl/regulamin': typeof PlRegulaminRoute
  '/pl/rezerwacja': typeof PlRezerwacjaRoute
  '/pl/sanktuarium': typeof PlSanktuariumRoute
  '/pl/tarot': typeof PlTarotRoute
  '/pl/uslugi': typeof PlUslugiRoute
  '/rytualy/$slug': typeof RytualySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/biblioteka/': typeof BibliotekaIndexRoute
  '/en/': typeof EnIndexRoute
  '/kronika/': typeof KronikaIndexRoute
  '/pl/': typeof PlIndexRoute
  '/rytualy/': typeof RytualyIndexRoute
  '/en/chronicle/consultations': typeof EnChronicleConsultationsRoute
  '/en/chronicle/notes': typeof EnChronicleNotesRoute
  '/en/chronicle/profile': typeof EnChronicleProfileRoute
  '/en/chronicle/reflections': typeof EnChronicleReflectionsRoute
  '/en/chronicle/rituals': typeof EnChronicleRitualsRoute
  '/en/library/$slug': typeof EnLibrarySlugRoute
  '/en/rituals/$slug': typeof EnRitualsSlugRoute
  '/pl/biblioteka/$slug': typeof PlBibliotekaSlugRoute
  '/pl/kronika/konsultacje': typeof PlKronikaKonsultacjeRoute
  '/pl/kronika/notatki': typeof PlKronikaNotatkiRoute
  '/pl/kronika/profil': typeof PlKronikaProfilRoute
  '/pl/kronika/refleksje': typeof PlKronikaRefleksjeRoute
  '/pl/kronika/rytualy': typeof PlKronikaRytualyRoute
  '/pl/rytualy/$slug': typeof PlRytualySlugRoute
  '/en/chronicle/': typeof EnChronicleIndexRoute
  '/en/library/': typeof EnLibraryIndexRoute
  '/en/rituals/': typeof EnRitualsIndexRoute
  '/pl/biblioteka/': typeof PlBibliotekaIndexRoute
  '/pl/kronika/': typeof PlKronikaIndexRoute
  '/pl/rytualy/': typeof PlRytualyIndexRoute
  '/api/public/telegram/admin': typeof ApiPublicTelegramAdminRoute
  '/api/public/telegram/stats': typeof ApiPublicTelegramStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/astrologia'
    | '/en'
    | '/faq'
    | '/gdzie-dzialam'
    | '/kontakt'
    | '/kronika'
    | '/o-mnie'
    | '/pl'
    | '/polityka-prywatnosci'
    | '/powrot'
    | '/regulamin'
    | '/rezerwacja'
    | '/robots.txt'
    | '/sanktuarium'
    | '/sitemap.xml'
    | '/tarot'
    | '/uslugi'
    | '/admin/aktywnosc'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/content'
    | '/admin/grafik'
    | '/admin/integrations'
    | '/admin/konsultacje'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/telegram'
    | '/admin/users'
    | '/biblioteka/$slug'
    | '/en/about'
    | '/en/astrology'
    | '/en/booking'
    | '/en/chronicle'
    | '/en/contact'
    | '/en/faq'
    | '/en/privacy-policy'
    | '/en/return'
    | '/en/sanctuary'
    | '/en/services'
    | '/en/tarot'
    | '/en/terms'
    | '/en/where-i-work'
    | '/kronika/konsultacje'
    | '/kronika/notatki'
    | '/kronika/profil'
    | '/kronika/refleksje'
    | '/kronika/rytualy'
    | '/pl/astrologia'
    | '/pl/faq'
    | '/pl/gdzie-dzialam'
    | '/pl/kontakt'
    | '/pl/kronika'
    | '/pl/o-mnie'
    | '/pl/polityka-prywatnosci'
    | '/pl/powrot'
    | '/pl/regulamin'
    | '/pl/rezerwacja'
    | '/pl/sanktuarium'
    | '/pl/tarot'
    | '/pl/uslugi'
    | '/rytualy/$slug'
    | '/admin/'
    | '/biblioteka/'
    | '/en/'
    | '/kronika/'
    | '/pl/'
    | '/rytualy/'
    | '/en/chronicle/consultations'
    | '/en/chronicle/notes'
    | '/en/chronicle/profile'
    | '/en/chronicle/reflections'
    | '/en/chronicle/rituals'
    | '/en/library/$slug'
    | '/en/rituals/$slug'
    | '/pl/biblioteka/$slug'
    | '/pl/kronika/konsultacje'
    | '/pl/kronika/notatki'
    | '/pl/kronika/profil'
    | '/pl/kronika/refleksje'
    | '/pl/kronika/rytualy'
    | '/pl/rytualy/$slug'
    | '/en/chronicle/'
    | '/en/library/'
    | '/en/rituals/'
    | '/pl/biblioteka/'
    | '/pl/kronika/'
    | '/pl/rytualy/'
    | '/api/public/telegram/admin'
    | '/api/public/telegram/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrologia'
    | '/faq'
    | '/gdzie-dzialam'
    | '/kontakt'
    | '/o-mnie'
    | '/polityka-prywatnosci'
    | '/powrot'
    | '/regulamin'
    | '/rezerwacja'
    | '/robots.txt'
    | '/sanktuarium'
    | '/sitemap.xml'
    | '/tarot'
    | '/uslugi'
    | '/admin/aktywnosc'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/content'
    | '/admin/grafik'
    | '/admin/integrations'
    | '/admin/konsultacje'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/telegram'
    | '/admin/users'
    | '/biblioteka/$slug'
    | '/en/about'
    | '/en/astrology'
    | '/en/booking'
    | '/en/contact'
    | '/en/faq'
    | '/en/privacy-policy'
    | '/en/return'
    | '/en/sanctuary'
    | '/en/services'
    | '/en/tarot'
    | '/en/terms'
    | '/en/where-i-work'
    | '/kronika/konsultacje'
    | '/kronika/notatki'
    | '/kronika/profil'
    | '/kronika/refleksje'
    | '/kronika/rytualy'
    | '/pl/astrologia'
    | '/pl/faq'
    | '/pl/gdzie-dzialam'
    | '/pl/kontakt'
    | '/pl/o-mnie'
    | '/pl/polityka-prywatnosci'
    | '/pl/powrot'
    | '/pl/regulamin'
    | '/pl/rezerwacja'
    | '/pl/sanktuarium'
    | '/pl/tarot'
    | '/pl/uslugi'
    | '/rytualy/$slug'
    | '/admin'
    | '/biblioteka'
    | '/en'
    | '/kronika'
    | '/pl'
    | '/rytualy'
    | '/en/chronicle/consultations'
    | '/en/chronicle/notes'
    | '/en/chronicle/profile'
    | '/en/chronicle/reflections'
    | '/en/chronicle/rituals'
    | '/en/library/$slug'
    | '/en/rituals/$slug'
    | '/pl/biblioteka/$slug'
    | '/pl/kronika/konsultacje'
    | '/pl/kronika/notatki'
    | '/pl/kronika/profil'
    | '/pl/kronika/refleksje'
    | '/pl/kronika/rytualy'
    | '/pl/rytualy/$slug'
    | '/en/chronicle'
    | '/en/library'
    | '/en/rituals'
    | '/pl/biblioteka'
    | '/pl/kronika'
    | '/pl/rytualy'
    | '/api/public/telegram/admin'
    | '/api/public/telegram/stats'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/astrologia'
    | '/en'
    | '/faq'
    | '/gdzie-dzialam'
    | '/kontakt'
    | '/kronika'
    | '/o-mnie'
    | '/pl'
    | '/polityka-prywatnosci'
    | '/powrot'
    | '/regulamin'
    | '/rezerwacja'
    | '/robots.txt'
    | '/sanktuarium'
    | '/sitemap.xml'
    | '/tarot'
    | '/uslugi'
    | '/admin/aktywnosc'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/content'
    | '/admin/grafik'
    | '/admin/integrations'
    | '/admin/konsultacje'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/telegram'
    | '/admin/users'
    | '/biblioteka/$slug'
    | '/en/about'
    | '/en/astrology'
    | '/en/booking'
    | '/en/chronicle'
    | '/en/contact'
    | '/en/faq'
    | '/en/privacy-policy'
    | '/en/return'
    | '/en/sanctuary'
    | '/en/services'
    | '/en/tarot'
    | '/en/terms'
    | '/en/where-i-work'
    | '/kronika/konsultacje'
    | '/kronika/notatki'
    | '/kronika/profil'
    | '/kronika/refleksje'
    | '/kronika/rytualy'
    | '/pl/astrologia'
    | '/pl/faq'
    | '/pl/gdzie-dzialam'
    | '/pl/kontakt'
    | '/pl/kronika'
    | '/pl/o-mnie'
    | '/pl/polityka-prywatnosci'
    | '/pl/powrot'
    | '/pl/regulamin'
    | '/pl/rezerwacja'
    | '/pl/sanktuarium'
    | '/pl/tarot'
    | '/pl/uslugi'
    | '/rytualy/$slug'
    | '/admin/'
    | '/biblioteka/'
    | '/en/'
    | '/kronika/'
    | '/pl/'
    | '/rytualy/'
    | '/en/chronicle/consultations'
    | '/en/chronicle/notes'
    | '/en/chronicle/profile'
    | '/en/chronicle/reflections'
    | '/en/chronicle/rituals'
    | '/en/library/$slug'
    | '/en/rituals/$slug'
    | '/pl/biblioteka/$slug'
    | '/pl/kronika/konsultacje'
    | '/pl/kronika/notatki'
    | '/pl/kronika/profil'
    | '/pl/kronika/refleksje'
    | '/pl/kronika/rytualy'
    | '/pl/rytualy/$slug'
    | '/en/chronicle/'
    | '/en/library/'
    | '/en/rituals/'
    | '/pl/biblioteka/'
    | '/pl/kronika/'
    | '/pl/rytualy/'
    | '/api/public/telegram/admin'
    | '/api/public/telegram/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AstrologiaRoute: typeof AstrologiaRoute
  EnRoute: typeof EnRouteWithChildren
  FaqRoute: typeof FaqRoute
  GdzieDzialamRoute: typeof GdzieDzialamRoute
  KontaktRoute: typeof KontaktRoute
  KronikaRoute: typeof KronikaRouteWithChildren
  OMnieRoute: typeof OMnieRoute
  PlRoute: typeof PlRouteWithChildren
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  PowrotRoute: typeof PowrotRoute
  RegulaminRoute: typeof RegulaminRoute
  RezerwacjaRoute: typeof RezerwacjaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SanktuariumRoute: typeof SanktuariumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarotRoute: typeof TarotRoute
  UslugiRoute: typeof UslugiRoute
  BibliotekaSlugRoute: typeof BibliotekaSlugRoute
  RytualySlugRoute: typeof RytualySlugRoute
  BibliotekaIndexRoute: typeof BibliotekaIndexRoute
  RytualyIndexRoute: typeof RytualyIndexRoute
  ApiPublicTelegramAdminRoute: typeof ApiPublicTelegramAdminRoute
  ApiPublicTelegramStatsRoute: typeof ApiPublicTelegramStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia': {
      id: '/astrologia'
      path: '/astrologia'
      fullPath: '/astrologia'
      preLoaderRoute: typeof AstrologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdzie-dzialam': {
      id: '/gdzie-dzialam'
      path: '/gdzie-dzialam'
      fullPath: '/gdzie-dzialam'
      preLoaderRoute: typeof GdzieDzialamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kronika': {
      id: '/kronika'
      path: '/kronika'
      fullPath: '/kronika'
      preLoaderRoute: typeof KronikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mnie': {
      id: '/o-mnie'
      path: '/o-mnie'
      fullPath: '/o-mnie'
      preLoaderRoute: typeof OMnieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl': {
      id: '/pl'
      path: '/pl'
      fullPath: '/pl'
      preLoaderRoute: typeof PlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powrot': {
      id: '/powrot'
      path: '/powrot'
      fullPath: '/powrot'
      preLoaderRoute: typeof PowrotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezerwacja': {
      id: '/rezerwacja'
      path: '/rezerwacja'
      fullPath: '/rezerwacja'
      preLoaderRoute: typeof RezerwacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanktuarium': {
      id: '/sanktuarium'
      path: '/sanktuarium'
      fullPath: '/sanktuarium'
      preLoaderRoute: typeof SanktuariumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aktywnosc': {
      id: '/admin/aktywnosc'
      path: '/aktywnosc'
      fullPath: '/admin/aktywnosc'
      preLoaderRoute: typeof AdminAktywnoscRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grafik': {
      id: '/admin/grafik'
      path: '/grafik'
      fullPath: '/admin/grafik'
      preLoaderRoute: typeof AdminGrafikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konsultacje': {
      id: '/admin/konsultacje'
      path: '/konsultacje'
      fullPath: '/admin/konsultacje'
      preLoaderRoute: typeof AdminKonsultacjeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/biblioteka/': {
      id: '/biblioteka/'
      path: '/biblioteka'
      fullPath: '/biblioteka/'
      preLoaderRoute: typeof BibliotekaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteka/$slug': {
      id: '/biblioteka/$slug'
      path: '/biblioteka/$slug'
      fullPath: '/biblioteka/$slug'
      preLoaderRoute: typeof BibliotekaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/astrology': {
      id: '/en/astrology'
      path: '/astrology'
      fullPath: '/en/astrology'
      preLoaderRoute: typeof EnAstrologyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/booking': {
      id: '/en/booking'
      path: '/booking'
      fullPath: '/en/booking'
      preLoaderRoute: typeof EnBookingRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/chronicle': {
      id: '/en/chronicle'
      path: '/chronicle'
      fullPath: '/en/chronicle'
      preLoaderRoute: typeof EnChronicleRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy-policy': {
      id: '/en/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/en/privacy-policy'
      preLoaderRoute: typeof EnPrivacyPolicyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/return': {
      id: '/en/return'
      path: '/return'
      fullPath: '/en/return'
      preLoaderRoute: typeof EnReturnRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/sanctuary': {
      id: '/en/sanctuary'
      path: '/sanctuary'
      fullPath: '/en/sanctuary'
      preLoaderRoute: typeof EnSanctuaryRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/services': {
      id: '/en/services'
      path: '/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/tarot': {
      id: '/en/tarot'
      path: '/tarot'
      fullPath: '/en/tarot'
      preLoaderRoute: typeof EnTarotRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/where-i-work': {
      id: '/en/where-i-work'
      path: '/where-i-work'
      fullPath: '/en/where-i-work'
      preLoaderRoute: typeof EnWhereIWorkRouteImport
      parentRoute: typeof EnRoute
    }
    '/kronika/': {
      id: '/kronika/'
      path: '/'
      fullPath: '/kronika/'
      preLoaderRoute: typeof KronikaIndexRouteImport
      parentRoute: typeof KronikaRoute
    }
    '/kronika/konsultacje': {
      id: '/kronika/konsultacje'
      path: '/konsultacje'
      fullPath: '/kronika/konsultacje'
      preLoaderRoute: typeof KronikaKonsultacjeRouteImport
      parentRoute: typeof KronikaRoute
    }
    '/kronika/notatki': {
      id: '/kronika/notatki'
      path: '/notatki'
      fullPath: '/kronika/notatki'
      preLoaderRoute: typeof KronikaNotatkiRouteImport
      parentRoute: typeof KronikaRoute
    }
    '/kronika/profil': {
      id: '/kronika/profil'
      path: '/profil'
      fullPath: '/kronika/profil'
      preLoaderRoute: typeof KronikaProfilRouteImport
      parentRoute: typeof KronikaRoute
    }
    '/kronika/refleksje': {
      id: '/kronika/refleksje'
      path: '/refleksje'
      fullPath: '/kronika/refleksje'
      preLoaderRoute: typeof KronikaRefleksjeRouteImport
      parentRoute: typeof KronikaRoute
    }
    '/kronika/rytualy': {
      id: '/kronika/rytualy'
      path: '/rytualy'
      fullPath: '/kronika/rytualy'
      preLoaderRoute: typeof KronikaRytualyRouteImport
      parentRoute: typeof KronikaRoute
    }
    '/pl/': {
      id: '/pl/'
      path: '/'
      fullPath: '/pl/'
      preLoaderRoute: typeof PlIndexRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/astrologia': {
      id: '/pl/astrologia'
      path: '/astrologia'
      fullPath: '/pl/astrologia'
      preLoaderRoute: typeof PlAstrologiaRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/faq': {
      id: '/pl/faq'
      path: '/faq'
      fullPath: '/pl/faq'
      preLoaderRoute: typeof PlFaqRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/gdzie-dzialam': {
      id: '/pl/gdzie-dzialam'
      path: '/gdzie-dzialam'
      fullPath: '/pl/gdzie-dzialam'
      preLoaderRoute: typeof PlGdzieDzialamRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/kontakt': {
      id: '/pl/kontakt'
      path: '/kontakt'
      fullPath: '/pl/kontakt'
      preLoaderRoute: typeof PlKontaktRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/kronika': {
      id: '/pl/kronika'
      path: '/kronika'
      fullPath: '/pl/kronika'
      preLoaderRoute: typeof PlKronikaRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/o-mnie': {
      id: '/pl/o-mnie'
      path: '/o-mnie'
      fullPath: '/pl/o-mnie'
      preLoaderRoute: typeof PlOMnieRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/polityka-prywatnosci': {
      id: '/pl/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/pl/polityka-prywatnosci'
      preLoaderRoute: typeof PlPolitykaPrywatnosciRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/powrot': {
      id: '/pl/powrot'
      path: '/powrot'
      fullPath: '/pl/powrot'
      preLoaderRoute: typeof PlPowrotRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/regulamin': {
      id: '/pl/regulamin'
      path: '/regulamin'
      fullPath: '/pl/regulamin'
      preLoaderRoute: typeof PlRegulaminRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/rezerwacja': {
      id: '/pl/rezerwacja'
      path: '/rezerwacja'
      fullPath: '/pl/rezerwacja'
      preLoaderRoute: typeof PlRezerwacjaRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/sanktuarium': {
      id: '/pl/sanktuarium'
      path: '/sanktuarium'
      fullPath: '/pl/sanktuarium'
      preLoaderRoute: typeof PlSanktuariumRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/tarot': {
      id: '/pl/tarot'
      path: '/tarot'
      fullPath: '/pl/tarot'
      preLoaderRoute: typeof PlTarotRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/uslugi': {
      id: '/pl/uslugi'
      path: '/uslugi'
      fullPath: '/pl/uslugi'
      preLoaderRoute: typeof PlUslugiRouteImport
      parentRoute: typeof PlRoute
    }
    '/rytualy/': {
      id: '/rytualy/'
      path: '/rytualy'
      fullPath: '/rytualy/'
      preLoaderRoute: typeof RytualyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rytualy/$slug': {
      id: '/rytualy/$slug'
      path: '/rytualy/$slug'
      fullPath: '/rytualy/$slug'
      preLoaderRoute: typeof RytualySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/chronicle/': {
      id: '/en/chronicle/'
      path: '/'
      fullPath: '/en/chronicle/'
      preLoaderRoute: typeof EnChronicleIndexRouteImport
      parentRoute: typeof EnChronicleRoute
    }
    '/en/chronicle/consultations': {
      id: '/en/chronicle/consultations'
      path: '/consultations'
      fullPath: '/en/chronicle/consultations'
      preLoaderRoute: typeof EnChronicleConsultationsRouteImport
      parentRoute: typeof EnChronicleRoute
    }
    '/en/chronicle/notes': {
      id: '/en/chronicle/notes'
      path: '/notes'
      fullPath: '/en/chronicle/notes'
      preLoaderRoute: typeof EnChronicleNotesRouteImport
      parentRoute: typeof EnChronicleRoute
    }
    '/en/chronicle/profile': {
      id: '/en/chronicle/profile'
      path: '/profile'
      fullPath: '/en/chronicle/profile'
      preLoaderRoute: typeof EnChronicleProfileRouteImport
      parentRoute: typeof EnChronicleRoute
    }
    '/en/chronicle/reflections': {
      id: '/en/chronicle/reflections'
      path: '/reflections'
      fullPath: '/en/chronicle/reflections'
      preLoaderRoute: typeof EnChronicleReflectionsRouteImport
      parentRoute: typeof EnChronicleRoute
    }
    '/en/chronicle/rituals': {
      id: '/en/chronicle/rituals'
      path: '/rituals'
      fullPath: '/en/chronicle/rituals'
      preLoaderRoute: typeof EnChronicleRitualsRouteImport
      parentRoute: typeof EnChronicleRoute
    }
    '/en/library/': {
      id: '/en/library/'
      path: '/library'
      fullPath: '/en/library/'
      preLoaderRoute: typeof EnLibraryIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/library/$slug': {
      id: '/en/library/$slug'
      path: '/library/$slug'
      fullPath: '/en/library/$slug'
      preLoaderRoute: typeof EnLibrarySlugRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/rituals/': {
      id: '/en/rituals/'
      path: '/rituals'
      fullPath: '/en/rituals/'
      preLoaderRoute: typeof EnRitualsIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/rituals/$slug': {
      id: '/en/rituals/$slug'
      path: '/rituals/$slug'
      fullPath: '/en/rituals/$slug'
      preLoaderRoute: typeof EnRitualsSlugRouteImport
      parentRoute: typeof EnRoute
    }
    '/pl/biblioteka/': {
      id: '/pl/biblioteka/'
      path: '/biblioteka'
      fullPath: '/pl/biblioteka/'
      preLoaderRoute: typeof PlBibliotekaIndexRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/biblioteka/$slug': {
      id: '/pl/biblioteka/$slug'
      path: '/biblioteka/$slug'
      fullPath: '/pl/biblioteka/$slug'
      preLoaderRoute: typeof PlBibliotekaSlugRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/kronika/': {
      id: '/pl/kronika/'
      path: '/'
      fullPath: '/pl/kronika/'
      preLoaderRoute: typeof PlKronikaIndexRouteImport
      parentRoute: typeof PlKronikaRoute
    }
    '/pl/kronika/konsultacje': {
      id: '/pl/kronika/konsultacje'
      path: '/konsultacje'
      fullPath: '/pl/kronika/konsultacje'
      preLoaderRoute: typeof PlKronikaKonsultacjeRouteImport
      parentRoute: typeof PlKronikaRoute
    }
    '/pl/kronika/notatki': {
      id: '/pl/kronika/notatki'
      path: '/notatki'
      fullPath: '/pl/kronika/notatki'
      preLoaderRoute: typeof PlKronikaNotatkiRouteImport
      parentRoute: typeof PlKronikaRoute
    }
    '/pl/kronika/profil': {
      id: '/pl/kronika/profil'
      path: '/profil'
      fullPath: '/pl/kronika/profil'
      preLoaderRoute: typeof PlKronikaProfilRouteImport
      parentRoute: typeof PlKronikaRoute
    }
    '/pl/kronika/refleksje': {
      id: '/pl/kronika/refleksje'
      path: '/refleksje'
      fullPath: '/pl/kronika/refleksje'
      preLoaderRoute: typeof PlKronikaRefleksjeRouteImport
      parentRoute: typeof PlKronikaRoute
    }
    '/pl/kronika/rytualy': {
      id: '/pl/kronika/rytualy'
      path: '/rytualy'
      fullPath: '/pl/kronika/rytualy'
      preLoaderRoute: typeof PlKronikaRytualyRouteImport
      parentRoute: typeof PlKronikaRoute
    }
    '/pl/rytualy/': {
      id: '/pl/rytualy/'
      path: '/rytualy'
      fullPath: '/pl/rytualy/'
      preLoaderRoute: typeof PlRytualyIndexRouteImport
      parentRoute: typeof PlRoute
    }
    '/pl/rytualy/$slug': {
      id: '/pl/rytualy/$slug'
      path: '/rytualy/$slug'
      fullPath: '/pl/rytualy/$slug'
      preLoaderRoute: typeof PlRytualySlugRouteImport
      parentRoute: typeof PlRoute
    }
    '/api/public/telegram/admin': {
      id: '/api/public/telegram/admin'
      path: '/api/public/telegram/admin'
      fullPath: '/api/public/telegram/admin'
      preLoaderRoute: typeof ApiPublicTelegramAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/stats': {
      id: '/api/public/telegram/stats'
      path: '/api/public/telegram/stats'
      fullPath: '/api/public/telegram/stats'
      preLoaderRoute: typeof ApiPublicTelegramStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAktywnoscRoute: typeof AdminAktywnoscRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminGrafikRoute: typeof AdminGrafikRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminKonsultacjeRoute: typeof AdminKonsultacjeRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAktywnoscRoute: AdminAktywnoscRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminGrafikRoute: AdminGrafikRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminKonsultacjeRoute: AdminKonsultacjeRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnChronicleRouteChildren {
  EnChronicleConsultationsRoute: typeof EnChronicleConsultationsRoute
  EnChronicleNotesRoute: typeof EnChronicleNotesRoute
  EnChronicleProfileRoute: typeof EnChronicleProfileRoute
  EnChronicleReflectionsRoute: typeof EnChronicleReflectionsRoute
  EnChronicleRitualsRoute: typeof EnChronicleRitualsRoute
  EnChronicleIndexRoute: typeof EnChronicleIndexRoute
}

const EnChronicleRouteChildren: EnChronicleRouteChildren = {
  EnChronicleConsultationsRoute: EnChronicleConsultationsRoute,
  EnChronicleNotesRoute: EnChronicleNotesRoute,
  EnChronicleProfileRoute: EnChronicleProfileRoute,
  EnChronicleReflectionsRoute: EnChronicleReflectionsRoute,
  EnChronicleRitualsRoute: EnChronicleRitualsRoute,
  EnChronicleIndexRoute: EnChronicleIndexRoute,
}

const EnChronicleRouteWithChildren = EnChronicleRoute._addFileChildren(
  EnChronicleRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnAstrologyRoute: typeof EnAstrologyRoute
  EnBookingRoute: typeof EnBookingRoute
  EnChronicleRoute: typeof EnChronicleRouteWithChildren
  EnContactRoute: typeof EnContactRoute
  EnFaqRoute: typeof EnFaqRoute
  EnPrivacyPolicyRoute: typeof EnPrivacyPolicyRoute
  EnReturnRoute: typeof EnReturnRoute
  EnSanctuaryRoute: typeof EnSanctuaryRoute
  EnServicesRoute: typeof EnServicesRoute
  EnTarotRoute: typeof EnTarotRoute
  EnTermsRoute: typeof EnTermsRoute
  EnWhereIWorkRoute: typeof EnWhereIWorkRoute
  EnIndexRoute: typeof EnIndexRoute
  EnLibrarySlugRoute: typeof EnLibrarySlugRoute
  EnRitualsSlugRoute: typeof EnRitualsSlugRoute
  EnLibraryIndexRoute: typeof EnLibraryIndexRoute
  EnRitualsIndexRoute: typeof EnRitualsIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnAstrologyRoute: EnAstrologyRoute,
  EnBookingRoute: EnBookingRoute,
  EnChronicleRoute: EnChronicleRouteWithChildren,
  EnContactRoute: EnContactRoute,
  EnFaqRoute: EnFaqRoute,
  EnPrivacyPolicyRoute: EnPrivacyPolicyRoute,
  EnReturnRoute: EnReturnRoute,
  EnSanctuaryRoute: EnSanctuaryRoute,
  EnServicesRoute: EnServicesRoute,
  EnTarotRoute: EnTarotRoute,
  EnTermsRoute: EnTermsRoute,
  EnWhereIWorkRoute: EnWhereIWorkRoute,
  EnIndexRoute: EnIndexRoute,
  EnLibrarySlugRoute: EnLibrarySlugRoute,
  EnRitualsSlugRoute: EnRitualsSlugRoute,
  EnLibraryIndexRoute: EnLibraryIndexRoute,
  EnRitualsIndexRoute: EnRitualsIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface KronikaRouteChildren {
  KronikaKonsultacjeRoute: typeof KronikaKonsultacjeRoute
  KronikaNotatkiRoute: typeof KronikaNotatkiRoute
  KronikaProfilRoute: typeof KronikaProfilRoute
  KronikaRefleksjeRoute: typeof KronikaRefleksjeRoute
  KronikaRytualyRoute: typeof KronikaRytualyRoute
  KronikaIndexRoute: typeof KronikaIndexRoute
}

const KronikaRouteChildren: KronikaRouteChildren = {
  KronikaKonsultacjeRoute: KronikaKonsultacjeRoute,
  KronikaNotatkiRoute: KronikaNotatkiRoute,
  KronikaProfilRoute: KronikaProfilRoute,
  KronikaRefleksjeRoute: KronikaRefleksjeRoute,
  KronikaRytualyRoute: KronikaRytualyRoute,
  KronikaIndexRoute: KronikaIndexRoute,
}

const KronikaRouteWithChildren =
  KronikaRoute._addFileChildren(KronikaRouteChildren)

interface PlKronikaRouteChildren {
  PlKronikaKonsultacjeRoute: typeof PlKronikaKonsultacjeRoute
  PlKronikaNotatkiRoute: typeof PlKronikaNotatkiRoute
  PlKronikaProfilRoute: typeof PlKronikaProfilRoute
  PlKronikaRefleksjeRoute: typeof PlKronikaRefleksjeRoute
  PlKronikaRytualyRoute: typeof PlKronikaRytualyRoute
  PlKronikaIndexRoute: typeof PlKronikaIndexRoute
}

const PlKronikaRouteChildren: PlKronikaRouteChildren = {
  PlKronikaKonsultacjeRoute: PlKronikaKonsultacjeRoute,
  PlKronikaNotatkiRoute: PlKronikaNotatkiRoute,
  PlKronikaProfilRoute: PlKronikaProfilRoute,
  PlKronikaRefleksjeRoute: PlKronikaRefleksjeRoute,
  PlKronikaRytualyRoute: PlKronikaRytualyRoute,
  PlKronikaIndexRoute: PlKronikaIndexRoute,
}

const PlKronikaRouteWithChildren = PlKronikaRoute._addFileChildren(
  PlKronikaRouteChildren,
)

interface PlRouteChildren {
  PlAstrologiaRoute: typeof PlAstrologiaRoute
  PlFaqRoute: typeof PlFaqRoute
  PlGdzieDzialamRoute: typeof PlGdzieDzialamRoute
  PlKontaktRoute: typeof PlKontaktRoute
  PlKronikaRoute: typeof PlKronikaRouteWithChildren
  PlOMnieRoute: typeof PlOMnieRoute
  PlPolitykaPrywatnosciRoute: typeof PlPolitykaPrywatnosciRoute
  PlPowrotRoute: typeof PlPowrotRoute
  PlRegulaminRoute: typeof PlRegulaminRoute
  PlRezerwacjaRoute: typeof PlRezerwacjaRoute
  PlSanktuariumRoute: typeof PlSanktuariumRoute
  PlTarotRoute: typeof PlTarotRoute
  PlUslugiRoute: typeof PlUslugiRoute
  PlIndexRoute: typeof PlIndexRoute
  PlBibliotekaSlugRoute: typeof PlBibliotekaSlugRoute
  PlRytualySlugRoute: typeof PlRytualySlugRoute
  PlBibliotekaIndexRoute: typeof PlBibliotekaIndexRoute
  PlRytualyIndexRoute: typeof PlRytualyIndexRoute
}

const PlRouteChildren: PlRouteChildren = {
  PlAstrologiaRoute: PlAstrologiaRoute,
  PlFaqRoute: PlFaqRoute,
  PlGdzieDzialamRoute: PlGdzieDzialamRoute,
  PlKontaktRoute: PlKontaktRoute,
  PlKronikaRoute: PlKronikaRouteWithChildren,
  PlOMnieRoute: PlOMnieRoute,
  PlPolitykaPrywatnosciRoute: PlPolitykaPrywatnosciRoute,
  PlPowrotRoute: PlPowrotRoute,
  PlRegulaminRoute: PlRegulaminRoute,
  PlRezerwacjaRoute: PlRezerwacjaRoute,
  PlSanktuariumRoute: PlSanktuariumRoute,
  PlTarotRoute: PlTarotRoute,
  PlUslugiRoute: PlUslugiRoute,
  PlIndexRoute: PlIndexRoute,
  PlBibliotekaSlugRoute: PlBibliotekaSlugRoute,
  PlRytualySlugRoute: PlRytualySlugRoute,
  PlBibliotekaIndexRoute: PlBibliotekaIndexRoute,
  PlRytualyIndexRoute: PlRytualyIndexRoute,
}

const PlRouteWithChildren = PlRoute._addFileChildren(PlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AstrologiaRoute: AstrologiaRoute,
  EnRoute: EnRouteWithChildren,
  FaqRoute: FaqRoute,
  GdzieDzialamRoute: GdzieDzialamRoute,
  KontaktRoute: KontaktRoute,
  KronikaRoute: KronikaRouteWithChildren,
  OMnieRoute: OMnieRoute,
  PlRoute: PlRouteWithChildren,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  PowrotRoute: PowrotRoute,
  RegulaminRoute: RegulaminRoute,
  RezerwacjaRoute: RezerwacjaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SanktuariumRoute: SanktuariumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarotRoute: TarotRoute,
  UslugiRoute: UslugiRoute,
  BibliotekaSlugRoute: BibliotekaSlugRoute,
  RytualySlugRoute: RytualySlugRoute,
  BibliotekaIndexRoute: BibliotekaIndexRoute,
  RytualyIndexRoute: RytualyIndexRoute,
  ApiPublicTelegramAdminRoute: ApiPublicTelegramAdminRoute,
  ApiPublicTelegramStatsRoute: ApiPublicTelegramStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
